version: '3'
services:
  db:
    image: "${MONGO_IMAGE}"   
    container_name: fhirwork-base
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - "./init:/docker-entrypoint-initdb.d"
      - "./mongo-volume:/data/db"
    environment:
      - MONGO_INITDB_DATABASE=amplifhir-db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
